export const PIZZA_REQUEST ="PIZZA_REQUEST"
export const PIZZA_SUCCESS = "PIZZA_SUCCESS"
export const PIZZA_FAILS = "PIZZA_FAILS"



export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVER_FROM_CART="REMOVE_FROM_CART"